CREATE TABLE IF NOT EXISTS test_types
(
    col_int1     INT1         DEFAULT 0,
    col_int2     INT2         DEFAULT 0,
    col_int3     INT3         DEFAULT 0,
    col_int4     INT4         DEFAULT 0,
    col_int5     INT8         DEFAULT 0,
    col_float4   FLOAT4       DEFAULT 0,
    col_float8   FLOAT8       DEFAULT 0,
    col_date     DATE,
    col_datetime DATETIME,
    col_decimal  DECIMAL      DEFAULT 0,
    col_numeric  NUMERIC      DEFAULT 0,
    col_double   DOUBLE       DEFAULT 0,
    col_char     CHAR(10)     DEFAULT '',
    col_varchar  VARCHAR(255) DEFAULT '',
    col_boolean  BOOLEAN      DEFAULT 0
);

INSERT INTO test_types(col_int1,
                       col_int2,
                       col_int3,
                       col_int4,
                       col_int5,
                       col_float4,
                       col_float8,
                       col_date,
                       col_datetime,
                       col_decimal,
                       col_numeric,
                       col_double,
                       col_char,
                       col_varchar,
                       col_boolean)
VALUES (127,
        32767,
        8388607,
        2147483647,
        9223372036854775807,
        3.4028,
        1.79761234,
        '1971-02-03',
        '1972-03-04 05:05:05',
        1.123,
        4.5678,
        9.876,
        'x',
        'qwerty',
        true);